builderapp/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from. import views


urlpatterns = [
    path('',views.home,name = 'home'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('ongoing', views.ongoing, name='ongoing'),
    path('completed', views.completed, name='completed'),
    path('upcoming', views.upcoming, name='upcoming'),
    path('contactus', views.contactus, name='contactus'),
    path('testimonial', views.testimonial, name='testimonial'),
    path('details_view', views.details, name='details'),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

builderproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('builderapp.urls')),
]

admin.site.site_header = "Admin Panel"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to Admin Portal"

builderapp/models.py
from django.db import models

# Create your models here.


class GeneralSettings(models.Model):
    logo = models.ImageField(upload_to='uploads/logo/')
    title = models.CharField(max_length=512, verbose_name='Title', blank=True, null=True)
    mobile_no = models.CharField(blank=False, null=False, max_length=20, verbose_name='Contact No (Mobile')
    phone_no = models.CharField(blank=True, null=True, max_length=20, verbose_name='Contact No (Phone)')
    facebook_link = models.CharField(blank=True, null=True, max_length=512, verbose_name='Facebook Link')
    youtube_link = models.CharField(blank=True, null=True, max_length=512, verbose_name='Youtube Link')
    instagram_link = models.CharField(blank=True, null=True, max_length=512, verbose_name='Instagram Link')
    linkedin_link = models.CharField(blank=True, null=True, max_length=512, verbose_name='Linkedin Link')
    twitter_link = models.CharField(blank=True, null=True, max_length=512, verbose_name='Twitter Link')
    footer = models.CharField(blank=True, null=True, max_length=1024, verbose_name='Footer')
    about_us = models.TextField(blank=True, null=True, max_length=4096, verbose_name='About Us')
    contact_us = models.TextField(blank=True, null=True, max_length=4096, verbose_name='Contact Us')
    motto = models.CharField(max_length=512, verbose_name='Motto', blank=True, null=True)

    def __str__(self):
        return self.title

    def logo_tag(self):
        from django.utils.html import mark_safe
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.logo.url))

    logo_tag.short_description = 'Logo'
    logo_tag.allow_tags = True

    class Meta:
        verbose_name_plural = "General Settings"


class Project(models.Model):
    name = models.CharField(max_length=256, blank=False)
    code = models.CharField(max_length=10, blank=False)
    start_date = models.DateField(default=None, blank=True)
    tentative_end_date = models.DateField(default=None, blank=True)
    image = models.ImageField(blank=True, upload_to='uploads/project/')
    project_value = models.DecimalField(max_length=15, max_digits=15, decimal_places=6)

    class Meta:
        verbose_name_plural = "Projects"


class ProjectImages(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to='uploads/project/')
    title = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.title


class Contact(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.email

    class Meta:
        verbose_name_plural = "Contacts"


class Testimonials(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Client Name')
    image = models.ImageField(blank=True, upload_to='uploads/testimonials/')
    message = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Testimonials"

builderapp/forms.py
from django.forms import ModelForm
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

builderapp/views.py
from django.shortcuts import render

# Create your views here.
from builderapp.forms import ContactForm
from django.shortcuts import redirect
from django.contrib import messages


def home(request):
    return render(request, 'index.html')

def aboutus(request):
    return render(request, 'aboutus.html')

def ongoing(request):
    return render(request, 'ongoing_project.html')

def upcoming(request):
    return render(request, 'upcoming_project.html')

def completed(request):
    return render(request, 'completed_project.html')


def contactus(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Thank You for contacting us. We will get back to you shortly!')
            return redirect('/contactus/')
    form = ContactForm()
    context = {'form': form}
    return render(request, 'contactus.html')

def testimonial(request):
    return render(request, 'testimonial.html')


def details(request):
    return render(request, 'details.html')

builderapp/templates/aboutus.html
{% include 'includes/header.html' %}
{% load static %}

<section class="header-title" style="background:url('{% static 'img/aboutusimage.jpg' %}')">
    <div class="container-fluid aboutus-header-title">
        <div class="container">
              <h4 class="text-white">About Us</h4>
        </div>


    </div>
</section>


<section class="about-us-content-section p-5">

    <div class="container">
            <div class="row justify-content-center">
                 <div class="col-12 col-md-6 d-flex flex-column justify-content-center pt-2">
                     <h2>Why you will choose us?</h2>
                    <h4 class="about-us-content-text">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci iste natus quasi reprehenderit sunt.
                        A consequatur corporis doloribus est eum eveniet, iure, magni maxime minus nulla quis, ut voluptatibus.
                        Possimus!
                         Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci iste natus quasi reprehenderit sunt.
                        A consequatur corporis doloribus est eum eveniet, iure, magni maxime minus nulla quis, ut voluptatibus.
                        Possimus!
                    </h4>
                </div>
                <div class="col-12 col-md-6 pt-2" style="background:url('')">
                    <img class="img-fluid shadow" src="{% static 'img/aboutusimg.jpg' %}" alt="">

                </div>
            </div>
    </div>

</section>






<!-- Swiper JS -->
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

<!-- Initialize Swiper -->


<!-- Script -->
{% include 'includes/footer.html' %}

builderapp/templates/completed_project.html
{% include 'includes/header.html' %}
{% load static %}

<section class="header-title" style="background:url('{% static 'img/aboutusimage.jpg' %}')">
    <div class="container-fluid aboutus-header-title">
        <div class="container">
              <h4 class="text-white">Completed Project</h4>
        </div>


    </div>
</section>


<section class=" ongoing-project-section pt-5 pb-5">
    <div class="container d-flex justify-content-center">
        <div class="col-12">
            <div class="row justify-content-center">
                <div class="col-12 col-md-3 p-2">
                    <div class="card" style="100%">
                        <img src="{%static 'img/demo.jpg'%}" class="card-img-top" alt="...">
                        <div class="card-body text-center">
                            <h5 class="card-title">Card title</h5>
                            <a href="#" class="btn btn-primary">View Details</a>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-3 p-2">
                    <div class="card" style="100%">
                        <img src="{%static 'img/demo.jpg'%}" class="card-img-top" alt="...">
                        <div class="card-body text-center">
                            <h5 class="card-title">Card title</h5>
                            <a href="#" class="btn btn-primary">View Details</a>
                        </div>
                    </div>
                </div>
                 <div class="col-12 col-md-3 p-2">
                    <div class="card" style="100%">
                        <img src="{%static 'img/demo.jpg'%}" class="card-img-top" alt="...">
                        <div class="card-body text-center">
                            <h5 class="card-title">Card title</h5>
                            <a href="#" class="btn btn-primary">View Details</a>
                        </div>
                    </div>
                </div>

                  <div class="col-12 col-md-3 p-2">
                    <div class="card" style="100%">
                        <img src="{%static 'img/demo.jpg'%}" class="card-img-top" alt="...">
                        <div class="card-body text-center">
                            <h5 class="card-title">Card title</h5>
                            <a href="#" class="btn btn-primary">View Details</a>
                        </div>
                    </div>
                </div>

                   <div class="col-12 col-md-3 p-2">
                    <div class="card" style="100%">
                        <img src="{%static 'img/demo.jpg'%}" class="card-img-top" alt="...">
                        <div class="card-body text-center">
                            <h5 class="card-title">Card title</h5>
                            <a href="#" class="btn btn-primary">View Details</a>
                        </div>
                    </div>
                </div>
                   <div class="col-12 col-md-3 p-2">
                    <div class="card" style="100%">
                        <img src="{%static 'img/demo.jpg'%}" class="card-img-top" alt="...">
                        <div class="card-body text-center">
                            <h5 class="card-title">Card title</h5>
                            <a href="#" class="btn btn-primary">View Details</a>
                        </div>
                    </div>
                </div>
                   <div class="col-12 col-md-3 p-2">
                    <div class="card" style="100%">
                        <img src="{%static 'img/demo.jpg'%}" class="card-img-top" alt="...">
                        <div class="card-body text-center">
                            <h5 class="card-title">Card title</h5>
                            <a href="#" class="btn btn-primary">View Details</a>
                        </div>
                    </div>
                </div>



            </div>

            <nav aria-label="..." class="d-flex justify-content-center mt-3" >
              <ul class="pagination">
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item active">
                  <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                </li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                  <a class="page-link" href="#">Next</a>
                </li>
              </ul>
            </nav>



        </div>
    </div>

</section>






<!-- Swiper JS -->
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

<!-- Initialize Swiper -->


<!-- Script -->
{% include 'includes/footer.html' %}

builderapp/templates/contactus.html
{% include 'includes/header.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
<section class="header-title" style="background:url('{% static 'img/aboutusimage.jpg' %}')">
    <div class="container-fluid aboutus-header-title">
        <div class="container">
              <h4 class="text-white">Contact Us</h4>
        </div>


    </div>
</section>


<section class="about-us-content-section p-5">

    <div class="container">
                    <form action="" method="post">
    <input type="hidden" name="csrfmiddlewaretoken" value="yTF5g7ceTgkwsOimKxZpuV10DG4a1TWFwQ60pneu047lPvu6kTAlNYPfYEC9G8jq">
    <tr>
        <th>
            <label for="id_email">Email:</label>
        </th>
        <td>
            <input type="email" name="email" maxlength="254" required id="id_email">
        </td>
    </tr>
    <tr>
        <th>
            <label for="id_subject">Subject:</label>
        </th>
        <td>
            <input type="text" name="subject" maxlength="255" required id="id_subject">
        </td>
    </tr>
    <tr>
        <th>
            <label for="id_message">Message:</label>
        </th>
        <td>
            <textarea name="message" cols="40" rows="10" required id="id_message"></textarea>
        </td>
    </tr>
    <input type="submit" value="Submit">
</form>
    </div>

</section>






<!-- Swiper JS -->
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

<!-- Initialize Swiper -->


<!-- Script -->
{% include 'includes/footer.html' %}

builderapp/templates/details.html
{% include 'includes/header.html' %}
{% load static %}

<section class="header-title" style="background:url('{% static 'img/aboutusimage.jpg' %}')">
    <div class="container-fluid aboutus-header-title">
        <div class="container">
              <h4 class="text-white">Titles of the post</h4>
            <p class="text-white">Date of the post : 12-10-2020</p>
        </div>


    </div>
</section>


<section class="about-us-content-section p-5 m-3">

         <div class="container mt-2">
            <div class="row justify-content-center" style="align-items: center;">

{#                There will be 2 or more picture, this image is cover picture of the post#}
                <div class="col-12 col-md-8 pt-2" style="background: url({%static 'img/demo.jpg'%}); height: 400px; background-size: cover; background-repeat: no-repeat; display: flex; justify-content: center;">
                     <img class="img-fluid" src="" alt="">
                </div>
                 <div class="col-12 col-md-8 d-flex flex-column justify-content-center pt-5 ">

                     <h2 style="font-size: 25px;" class="about-us-content-text">Title of the post </h2>
                    <h4 class="about-us-content-text">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci iste natus quasi reprehenderit sunt.
                        A consequatur corporis doloribus est eum eveniet, iure, magni maxime minus nulla quis, ut voluptatibus.
                        Possimus!
                         Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci iste natus quasi reprehenderit sunt.
                        A consequatur corporis doloribus est eum eveniet, iure, magni maxime minus nulla quis, ut voluptatibus.
                        Possimus!
                    </h4>
                     <p>By -Mr.Pk Halder</p>
                </div>

                <div class="col-12 col-md-4 pt-2 m-2" style="background: url({%static 'img/demo.jpg'%}); height: 400px; background-size: cover; background-repeat: no-repeat; display: flex; justify-content: center;">
                     <img class="img-fluid" src="" alt="">
                </div>
                 <div class="col-12 col-md-4 pt-2 m-2" style="background: url({%static 'img/demo.jpg'%}); height: 400px; background-size: cover; background-repeat: no-repeat; display: flex; justify-content: center;">
                     <img class="img-fluid" src="" alt="">
                </div>






            </div>
    </div>








</section>






<!-- Swiper JS -->
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

<!-- Initialize Swiper -->


<!-- Script -->
{% include 'includes/footer.html' %}

builderapp/templates/includes/footer.html
{% load static %}
<section class="py-5 bg-voilet text-white footer">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <img class="img-fluid" style="height: auto; width: 140px; padding-left: 8px;"
                     src="{% static 'img/logo.png' %}" alt="">
                <p>{{ setting.footer }}</p>

            </div>
            <div class="col-md-3">
                <h4><b>Quick Links</b></h4>
                <ul class="list-unstyled mt-3">
                    <li><a href="#" class="text-white">How it works?</a></li>
                    <div class="mb-2"></div>
                    <li><a href="#" class="text-white">Career</a></li>
                    <div class="mb-2"></div>
                    <li><a href="#" class="text-white">Privacy Policy</a></li>
                    <div class="mb-2"></div>
                    <li><a href="#" class="text-white">Terms & Conditions</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <h4><b>Support</b></h4>
                <ul class="list-unstyled mt-3">
                    <li><a href="#" class="text-white">About Us</a></li>
                    <div class="mb-2"></div>
                    <li><a href="#" class="text-white">Contact Us</a></li>
                    <div class="mb-2"></div>
                    <li><a href="#" class="text-white">Our Team</a></li>
                    <div class="mb-2"></div>
                    <li><a href="#" class="text-white">Testimonials</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <h4><b>Contact Us</b></h4>
                <ul class="list-unstyled mt-3">
                    <li><a href="#" class="text-white">How it works?</a></li>
                    <div class="mb-2"></div>
                    <li><a href="#" class="text-white">Career</a></li>
                    <div class="mb-2"></div>
                    <li><a href="#" class="text-white">Privacy Policy</a></li>
                    <div class="mb-2"></div>
                    <li><a href="#" class="text-white">Terms & Conditions</a></li>
                </ul>
            </div>
        </div>
    </div>
</section>


<!-- Script -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js"></script>

<script>

// vars
'use strict'
var	testim = document.getElementById("testim"),
		testimDots = Array.prototype.slice.call(document.getElementById("testim-dots").children),
    testimContent = Array.prototype.slice.call(document.getElementById("testim-content").children),
    testimLeftArrow = document.getElementById("left-arrow"),
    testimRightArrow = document.getElementById("right-arrow"),
    testimSpeed = 4500,
    currentSlide = 0,
    currentActive = 0,
    testimTimer,
		touchStartPos,
		touchEndPos,
		touchPosDiff,
		ignoreTouch = 30;
;

window.onload = function() {

    // Testim Script
    function playSlide(slide) {
        for (var k = 0; k < testimDots.length; k++) {
            testimContent[k].classList.remove("active");
            testimContent[k].classList.remove("inactive");
            testimDots[k].classList.remove("active");
        }

        if (slide < 0) {
            slide = currentSlide = testimContent.length-1;
        }

        if (slide > testimContent.length - 1) {
            slide = currentSlide = 0;
        }

        if (currentActive != currentSlide) {
            testimContent[currentActive].classList.add("inactive");
        }
        testimContent[slide].classList.add("active");
        testimDots[slide].classList.add("active");

        currentActive = currentSlide;

        clearTimeout(testimTimer);
        testimTimer = setTimeout(function() {
            playSlide(currentSlide += 1);
        }, testimSpeed)
    }

    testimLeftArrow.addEventListener("click", function() {
        playSlide(currentSlide -= 1);
    })

    testimRightArrow.addEventListener("click", function() {
        playSlide(currentSlide += 1);
    })

    for (var l = 0; l < testimDots.length; l++) {
        testimDots[l].addEventListener("click", function() {
            playSlide(currentSlide = testimDots.indexOf(this));
        })
    }

    playSlide(currentSlide);

    // keyboard shortcuts
    document.addEventListener("keyup", function(e) {
        switch (e.keyCode) {
            case 37:
                testimLeftArrow.click();
                break;

            case 39:
                testimRightArrow.click();
                break;

            case 39:
                testimRightArrow.click();
                break;

            default:
                break;
        }
    })

		testim.addEventListener("touchstart", function(e) {
				touchStartPos = e.changedTouches[0].clientX;
		})

		testim.addEventListener("touchend", function(e) {
				touchEndPos = e.changedTouches[0].clientX;

				touchPosDiff = touchStartPos - touchEndPos;

				console.log(touchPosDiff);
				console.log(touchStartPos);
				console.log(touchEndPos);


				if (touchPosDiff > 0 + ignoreTouch) {
						testimLeftArrow.click();
				} else if (touchPosDiff < 0 - ignoreTouch) {
						testimRightArrow.click();
				} else {
					return;
				}

		})
}

</script>
<!-- Script -->
</body>
</html>

builderapp/templates/includes/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% if setting.title %}{{ setting.tile }}{% else %}Builder Project{% endif %}</title>
    <link rel="icon"href="{% static 'favicon.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
</head>
<body>
<section class="header">

    <div class="container-fluid header-top bg-gradient1">
        <div class="container">
            <div class="row p-2 justify-content-center">
                <div class="col-12 col-sm-12 col-md-12 col-lg-4 justify-content-center justify-content-lg-start ml7">
                    <span class="text-wrapper"><span class="letters">the art of living..</span></span></div>
                <div class="col-12 col-lg-3 d-none d-md-block contact-default">
                    <p>
                        <span>+88 {% if setting.mobile_no %}{{ setting.mobile_no }}{% else %} 018522330000{% endif %}</span>
                    </p>
                <p>
                    <span>{% if setting.mobile_no %}{{ setting.phone_no }}{% else %} 018522330000{% endif %}</span>
                </p>
                </div>
                <div class="col-12 col-lg-5 justify-content-center justify-content-lg-end header-social-icon">
                    <p>FOLLOW US : </p>
                    <a href="{% if setting.facebook_link %}{{ setting.facebook_link }}{% else %}#{% endif %}"><i class="fab fa-facebook-square"></i></a>
                    <a href="{% if setting.twitter_link %}{{ setting.twitter_link }}{% else %}#{% endif %}"><i class="fab fa-twitter-square"></i></a>
                    <a href="{% if setting.youtube_link %}{{ setting.youtube_link }}{% else %}#{% endif %}"><i class="fab fa-youtube-square"></i></a>
                    <a href="{% if setting.linkedin_link %}{{ setting.linkedin_link }}{% else %}#{% endif %}"><i class="fab fa-linkedin"></i></a>
                    <a href="{% if setting.instagram_link %}{{ setting.instagram_link }}{% else %}#{% endif %}"><i class="fab fa-instagram-square"></i></a>

                </div>
            </div>
        </div>
    </div>
    <div id="navbar_top" class="container-fluid bg-white">
        <div id="" class="container header-bottom bg-white">
        <nav class="navbar navbar-expand-lg navbar-light ">
            <a class="navbar-brand" href="#">
                <img class="img-fluid" style="height: auto; width: 140px; padding-left: 8px;"
                     src="{% static 'img/logo.png' %}" alt="">
            </a>
           <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
            {% block messages %}
                        {% if messages %}
                        {% for message in messages %}
                          <div class="alert alert-{% firstof message.tags 'info' %}">
                            <button class="close" data-dismiss="alert">×</button>
                            {{ message }}
                          </div>
                        {% endfor %}
                    {% endif %}
                    {% endblock messages %}
            <div class="collapse navbar-collapse header-menu-flex-end" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                  <li class="nav-item dropdown ">
                       <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">Projects</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'ongoing' %}">Ongoing</a></li>
                            <li><a class="dropdown-item" href="{% url 'upcoming' %}">Upcoming</a></li>
                            <li><a class="dropdown-item" href="{% url 'completed' %}">Completed</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'testimonial' %}">Testimonials</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'aboutus' %}">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contactus' %}">Contact Us</a>
                    </li>

                </ul>
            </div>
        </nav>
    </div>
    </div>


</section>

<script>
    // Wrap every letter in a span
    var textWrapper = document.querySelector('.ml7 .letters');
    textWrapper.innerHTML = textWrapper.textContent.replace(/\S/g, "<span class='letter'>$&</span>");

    anime.timeline({loop: true})
        .add({
            targets: '.ml7 .letter',
            translateY: ["1.1em", 0],
            translateX: ["0.55em", 0],
            translateZ: 0,
            rotateZ: [180, 0],
            duration: 750,
            easing: "easeOutExpo",
            delay: (el, i) => 50 * i
        }).add({
        targets: '.ml7',
        opacity: 0,
        duration: 1000,
        easing: "easeOutExpo",
        delay: 1000
    });

    document.addEventListener("DOMContentLoaded", function(){
  window.addEventListener('scroll', function() {
      if (window.scrollY > 50) {
        document.getElementById('navbar_top').classList.add('fixed-top');
        // add padding top to show content behind navbar
        navbar_height = document.querySelector('.navbar').offsetHeight;
        document.body.style.paddingTop = navbar_height + 'px';
      } else {
        document.getElementById('navbar_top').classList.remove('fixed-top');
         // remove padding top from body
        document.body.style.paddingTop = '0';
      }
  });
});


</script>